apiVersion: apps/v1
kind: Deployment
metadata:
  name: hermes-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hermes
  template:
    metadata:
      labels:
        app: hermes
    spec:
      containers:
        - name: hermes-container
          image: aziztesteur95100/hermes-tests:latest
          ports:
            - containerPort: 80
